# Generated by Django 5.2.16 on 2026-08-08 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('company_name', models.CharField(max_length=200)),
                ('contact_person', models.CharField(max_length=150)),
                ('supplier_type', models.CharField(choices=[('manufacturer', 'Manufacturer'), ('distributor', 'Distributor'), ('wholesaler', 'Wholesaler'), ('retailer', 'Retailer')], default='distributor', max_length=30)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='suppliers/')),
                ('phone', models.CharField(max_length=30)),
                ('alternate_phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField(blank=True)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('pin_code', models.CharField(max_length=20)),
                ('gstin', models.CharField(blank=True, max_length=30)),
                ('pan', models.CharField(blank=True, max_length=30)),
                ('tax_reg_type', models.CharField(choices=[('regular', 'Regular'), ('composition', 'Composition'), ('unregistered', 'Unregistered')], default='regular', max_length=30)),
                ('bank_name', models.CharField(blank=True, max_length=150)),
                ('holder_name', models.CharField(blank=True, max_length=150)),
                ('account_number', models.CharField(blank=True, max_length=50)),
                ('ifsc_code', models.CharField(blank=True, max_length=30)),
                ('branch', models.CharField(blank=True, max_length=100)),
                ('payment_terms', models.CharField(default='Net 30', help_text='e.g. Net 30, Net 60, COD', max_length=100)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('outstanding_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('due_days', models.IntegerField(default=30)),
                ('notes', models.TextField(blank=True)),
                ('internal_remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupplierHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('detail', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='suppliers.supplier')),
            ],
            options={
                'verbose_name_plural': 'Supplier Histories',
                'ordering': ['-created_at'],
            },
        ),
    ]
