# Generated by Django 5.2.16 on 2026-08-09 06:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLogSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retention_days', models.IntegerField(default=90)),
                ('log_views_enabled', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SystemAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user_role', models.CharField(default='System User', max_length=50)),
                ('action', models.CharField(db_index=True, max_length=50)),
                ('module', models.CharField(db_index=True, max_length=50)),
                ('record_type', models.CharField(blank=True, max_length=50, null=True)),
                ('record_id', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('unauthorized', 'Unauthorized / Denied')], default='success', max_length=20)),
                ('ip_address', models.CharField(blank=True, max_length=45, null=True)),
                ('device_info', models.CharField(blank=True, max_length=255, null=True)),
                ('before_data', models.JSONField(blank=True, null=True)),
                ('after_data', models.JSONField(blank=True, null=True)),
                ('changed_fields', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
