# Generated by Django 5.2.16 on 2026-08-09 11:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0004_alter_warehousestock_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BarcodeLabelPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('width_mm', models.IntegerField(default=50)),
                ('height_mm', models.IntegerField(default=30)),
                ('show_product_name', models.BooleanField(default=True)),
                ('show_price', models.BooleanField(default=True)),
                ('show_sku', models.BooleanField(default=True)),
                ('show_unit', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='BarcodeScanHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('barcode_value', models.CharField(max_length=100)),
                ('scan_mode', models.CharField(choices=[('lookup', 'Product Lookup'), ('stock_in', 'Stock In'), ('stock_out', 'Stock Out'), ('purchase', 'Purchase Entry'), ('transfer', 'Stock Transfer'), ('counting', 'Stock Counting')], default='lookup', max_length=30)),
                ('status', models.CharField(choices=[('found', 'Product Found'), ('not_found', 'Product Not Found'), ('invalid', 'Invalid Barcode'), ('duplicate', 'Duplicate Barcode')], default='found', max_length=20)),
                ('quantity', models.IntegerField(default=1)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='barcode_scans', to='products.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.warehouse')),
            ],
            options={
                'verbose_name_plural': 'Barcode Scan Histories',
                'ordering': ['-timestamp'],
            },
        ),
    ]
