# Generated by Django 5.2.16 on 2026-08-09 12:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barcodes', '0001_initial'),
        ('products', '0005_product_has_batch_tracking_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('scan_mode', models.CharField(choices=[('lookup', 'Product Lookup'), ('receiving', 'Goods Receiving'), ('stock_in', 'Stock In'), ('stock_out', 'Stock Out'), ('transfer', 'Stock Transfer'), ('stock_count', 'Stock Counting'), ('bin_lookup', 'Bin Location Lookup'), ('batch_lookup', 'Batch Lookup'), ('serial_lookup', 'Serial Number Lookup')], default='lookup', max_length=30)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('total_scans', models.IntegerField(default=0)),
                ('successful_scans', models.IntegerField(default=0)),
                ('failed_scans', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_sessions', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_sessions', to='products.warehouse')),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='ScanSessionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode_value', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('warning', 'Warning')], default='success', max_length=20)),
                ('message', models.CharField(blank=True, max_length=255)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='barcodes.scansession')),
            ],
            options={
                'ordering': ['-scanned_at'],
            },
        ),
    ]
