# Generated by Django 5.2.16 on 2026-08-09 06:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_backup_enabled', models.BooleanField(default=True)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', max_length=20)),
                ('backup_time', models.CharField(default='02:00', max_length=10)),
                ('retention_policy', models.CharField(choices=[('keep_5', 'Keep Last 5 Backups'), ('keep_10', 'Keep Last 10 Backups'), ('keep_30', 'Keep Last 30 Backups'), ('custom', 'Custom Retention Count')], default='keep_10', max_length=20)),
                ('custom_retention_count', models.IntegerField(default=10)),
                ('storage_location', models.CharField(default='Local Server Storage', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BackupRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backup_id', models.CharField(max_length=50, unique=True)),
                ('backup_name', models.CharField(max_length=150)),
                ('backup_type', models.CharField(choices=[('manual', 'Manual Backup'), ('automatic', 'Automatic Scheduled'), ('scheduled', 'Scheduled System Backup'), ('before_restore', 'Safety Backup (Before Restore)'), ('before_update', 'Pre-Update Safety Backup')], default='manual', max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('restoring', 'Restoring'), ('restore_completed', 'Restore Completed'), ('restore_failed', 'Restore Failed')], default='pending', max_length=30)),
                ('verification_status', models.CharField(choices=[('verified', 'Verified Integrity'), ('failed', 'Verification Failed'), ('pending', 'Pending Verification')], default='pending', max_length=30)),
                ('file_path', models.CharField(blank=True, max_length=255, null=True)),
                ('file_size_bytes', models.BigIntegerField(default=0)),
                ('checksum_sha256', models.CharField(blank=True, max_length=64, null=True)),
                ('database_size_bytes', models.BigIntegerField(default=0)),
                ('media_size_bytes', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backups_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
