# Generated by Django 5.2.16 on 2026-08-09 05:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0003_warehousestock_batch_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_stock', models.IntegerField(default=0)),
                ('physical_stock', models.IntegerField(default=0)),
                ('difference_quantity', models.IntegerField(default=0, help_text='Physical Stock minus Current Stock')),
                ('reason', models.CharField(choices=[('audit_discrepancy', 'Physical Audit Discrepancy'), ('damaged_goods', 'Damaged Goods'), ('expired_stock', 'Expired Stock'), ('found_stock', 'Found / Extra Stock'), ('theft_loss', 'Theft / Mysterious Loss'), ('other', 'Other Reason')], default='audit_discrepancy', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_adjustments', to='products.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_adjustments', to='products.warehouse')),
            ],
            options={
                'verbose_name_plural': 'Stock Adjustments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('purchase', 'Purchase'), ('purchase_return', 'Purchase Return'), ('stock_in', 'Stock In'), ('stock_out', 'Stock Out'), ('transfer_in', 'Stock Transfer In'), ('transfer_out', 'Stock Transfer Out'), ('adjustment', 'Stock Adjustment'), ('opening_stock', 'Opening Stock'), ('damaged', 'Damaged'), ('expired', 'Expired'), ('other', 'Other')], max_length=40)),
                ('quantity', models.IntegerField(help_text='Signed integer: positive for stock addition, negative for stock deduction')),
                ('previous_stock', models.IntegerField(default=0)),
                ('new_stock', models.IntegerField(default=0)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='products.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='products.warehouse')),
            ],
            options={
                'verbose_name_plural': 'Stock Movements',
                'ordering': ['-created_at'],
            },
        ),
    ]
