# Generated by Django 5.2.16 on 2026-08-09 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0005_product_has_batch_tracking_and_more'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(db_index=True, max_length=100)),
                ('purchase_invoice', models.CharField(blank=True, max_length=100)),
                ('mfg_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, db_index=True, null=True)),
                ('initial_quantity', models.IntegerField(default=0)),
                ('available_quantity', models.IntegerField(default=0)),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('selling_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('status', models.CharField(choices=[('active', 'Active Stock'), ('expiring_soon', 'Expiring Soon'), ('expired', 'Expired'), ('recalled', 'Recalled'), ('exhausted', 'Exhausted')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='products.product')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='suppliers.supplier')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='products.warehouse')),
            ],
            options={
                'verbose_name_plural': 'Product Batches',
                'ordering': ['expiry_date', '-created_at'],
                'unique_together': {('batch_number', 'product', 'warehouse')},
            },
        ),
        migrations.CreateModel(
            name='ProductSerialNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(db_index=True, max_length=100, unique=True)),
                ('purchase_invoice', models.CharField(blank=True, max_length=100)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('warranty_start', models.DateField(blank=True, null=True)),
                ('warranty_end', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('in_stock', 'In Stock'), ('sold', 'Sold'), ('transferred', 'Transferred'), ('reserved', 'Reserved'), ('damaged', 'Damaged'), ('returned', 'Returned'), ('under_repair', 'Under Repair'), ('lost', 'Lost'), ('disposed', 'Disposed')], default='in_stock', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='serials', to='batches.productbatch')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serials', to='products.product')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='serials', to='suppliers.supplier')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='serials', to='products.warehouse')),
            ],
            options={
                'verbose_name_plural': 'Product Serial Numbers',
                'ordering': ['-created_at'],
            },
        ),
    ]
