# Generated by Django 5.2.16 on 2026-08-09 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr_scanner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocrscanaudit',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
