# Generated by Django 5.2.16 on 2026-08-09 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('invoice', 'Sales Invoice'), ('purchase_order', 'Purchase Order'), ('grn', 'Goods Receipt Note'), ('transfer', 'Stock Transfer'), ('adjustment', 'Stock Adjustment'), ('sales_return', 'Sales Return'), ('purchase_return', 'Purchase Return'), ('employee', 'Employee Code'), ('customer', 'Customer Code'), ('supplier', 'Supplier Code')], db_index=True, max_length=40, unique=True)),
                ('prefix', models.CharField(default='DOC-', max_length=20)),
                ('next_number', models.IntegerField(default=1)),
                ('padding', models.IntegerField(default=6, help_text='Number of digits e.g. 6 -> INV-000001')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['document_type'],
            },
        ),
        migrations.CreateModel(
            name='SecurityPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_failed_attempts', models.IntegerField(default=5)),
                ('lockout_duration_mins', models.IntegerField(default=30)),
                ('min_password_length', models.IntegerField(default=8)),
                ('require_uppercase', models.BooleanField(default=True)),
                ('require_number', models.BooleanField(default=True)),
                ('require_special_char', models.BooleanField(default=True)),
                ('inactivity_timeout_mins', models.IntegerField(default=30)),
                ('enable_maintenance_mode', models.BooleanField(default=False)),
                ('maintenance_message', models.TextField(default='StockFlow AI is currently undergoing scheduled maintenance. Please check back shortly.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Security Policies',
            },
        ),
        migrations.CreateModel(
            name='UserFailedLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=150)),
                ('ip_address', models.CharField(blank=True, max_length=50)),
                ('attempt_time', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-attempt_time'],
            },
        ),
    ]
