# Generated by Django 5.2.16 on 2026-08-09 06:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(default='REG-2026-IN889', max_length=50)),
                ('gstin', models.CharField(default='09AAACS1234F1Z5', max_length=20)),
                ('pan', models.CharField(default='AAACS1234F', max_length=20)),
                ('cin', models.CharField(blank=True, default='U72900UP2026PTC123456', max_length=30, null=True)),
                ('tax_type', models.CharField(default='Regular Scheme', max_length=50)),
                ('industry', models.CharField(default='Electronics & FMCG Distribution', max_length=100)),
                ('description', models.TextField(default='Enterprise Multi-Warehouse Inventory & Supply Chain Management System')),
                ('fy_start_date', models.DateField(default=datetime.date(2026, 4, 1))),
                ('fy_end_date', models.DateField(default=datetime.date(2027, 3, 31))),
            ],
        ),
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='StockFlow Enterprise Pvt Ltd', max_length=150)),
                ('legal_name', models.CharField(default='StockFlow Enterprise Private Limited', max_length=150)),
                ('business_type', models.CharField(default='Private Limited Company', max_length=100)),
                ('email', models.EmailField(default='contact@stockflow.ai', max_length=254)),
                ('phone', models.CharField(default='+91 9876543210', max_length=20)),
                ('alt_phone', models.CharField(blank=True, default='+91 1123456789', max_length=20, null=True)),
                ('website', models.URLField(default='https://stockflow.ai')),
                ('address', models.TextField(default='Plot 42, Tech Park Sector 62')),
                ('city', models.CharField(default='Noida', max_length=100)),
                ('state', models.CharField(default='Uttar Pradesh', max_length=100)),
                ('country', models.CharField(default='India', max_length=100)),
                ('pin_code', models.CharField(default='201301', max_length=10)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='company/logos/')),
            ],
        ),
        migrations.CreateModel(
            name='CurrencySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_code', models.CharField(default='INR', max_length=10)),
                ('currency_symbol', models.CharField(default='₹', max_length=5)),
                ('country', models.CharField(default='India', max_length=50)),
                ('timezone', models.CharField(default='Asia/Kolkata', max_length=50)),
                ('date_format', models.CharField(default='DD/MM/YYYY', max_length=20)),
                ('number_format', models.CharField(default='1,50,000.00', max_length=20)),
                ('decimal_places', models.IntegerField(default=2)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valuation_method', models.CharField(choices=[('FIFO', 'First In First Out (FIFO)'), ('WEIGHTED_AVG', 'Weighted Average'), ('MOVING_AVG', 'Moving Average')], default='FIFO', max_length=20)),
                ('low_stock_threshold_default', models.IntegerField(default=10)),
                ('batch_tracking', models.BooleanField(default=True)),
                ('expiry_tracking', models.BooleanField(default=True)),
                ('serial_number_tracking', models.BooleanField(default=False)),
                ('barcode_tracking', models.BooleanField(default=True)),
                ('qr_code_tracking', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_prefix', models.CharField(default='INV-', max_length=10)),
                ('purchase_prefix', models.CharField(default='PUR-', max_length=10)),
                ('po_prefix', models.CharField(default='PO-', max_length=10)),
                ('transfer_prefix', models.CharField(default='TRF-', max_length=10)),
                ('starting_invoice_number', models.IntegerField(default=1001)),
                ('date_format', models.CharField(default='YYYY-MM-DD', max_length=20)),
                ('footer_text', models.TextField(default='Thank you for choosing StockFlow AI Enterprise Solutions.')),
                ('terms_conditions', models.TextField(default='1. Goods once sold cannot be returned without authorization.\n2. Interest @ 18% p.a. charged on overdue invoices.')),
                ('show_gstin', models.BooleanField(default=True)),
                ('show_hsn', models.BooleanField(default=True)),
                ('show_discount', models.BooleanField(default=True)),
                ('show_payment_details', models.BooleanField(default=True)),
                ('authorized_signature', models.ImageField(blank=True, null=True, upload_to='company/signatures/')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_low_stock', models.BooleanField(default=True)),
                ('notify_out_of_stock', models.BooleanField(default=True)),
                ('notify_purchase_created', models.BooleanField(default=True)),
                ('notify_purchase_approved', models.BooleanField(default=True)),
                ('notify_stock_transfer', models.BooleanField(default=True)),
                ('notify_ocr_completed', models.BooleanField(default=True)),
                ('notify_user_login', models.BooleanField(default=True)),
                ('channel_email', models.BooleanField(default=True)),
                ('channel_in_app', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='OCRAISettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('gemini', 'Google Gemini AI Engine'), ('tesseract', 'Tesseract OCR Engine'), ('google_vision', 'Google Cloud Vision API'), ('azure', 'Azure Document Intelligence'), ('aws', 'AWS Textract')], default='gemini', max_length=30)),
                ('api_key_masked', models.CharField(default='AIzaSy********************', max_length=200)),
                ('model_name', models.CharField(default='gemini-1.5-pro', max_length=50)),
                ('confidence_threshold', models.IntegerField(default=75)),
                ('max_file_size_mb', models.IntegerField(default=20)),
                ('allowed_file_types', models.CharField(default='PDF, JPG, JPEG, PNG, WEBP', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_order_required', models.BooleanField(default=True)),
                ('purchase_approval_required', models.BooleanField(default=True)),
                ('goods_receipt_required', models.BooleanField(default=True)),
                ('allow_partial_receiving', models.BooleanField(default=True)),
                ('allow_purchase_return', models.BooleanField(default=True)),
                ('duplicate_invoice_detection', models.BooleanField(default=True)),
                ('default_payment_terms', models.CharField(default='Net 30 Days', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SecuritySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_timeout_minutes', models.IntegerField(default=30)),
                ('password_min_length', models.IntegerField(default=8)),
                ('password_expiry_days', models.IntegerField(default=90)),
                ('max_login_attempts', models.IntegerField(default=5)),
                ('account_lockout_minutes', models.IntegerField(default=15)),
                ('require_strong_password', models.BooleanField(default=True)),
                ('enable_two_factor', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SystemPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('light', 'Light Mode'), ('dark', 'Dark Mode'), ('auto', 'System Default')], default='auto', max_length=10)),
                ('items_per_page', models.IntegerField(default=25)),
                ('default_report_period', models.CharField(default='this_month', max_length=20)),
                ('compact_table_mode', models.BooleanField(default=False)),
                ('enable_animations', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaxSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gst_enabled', models.BooleanField(default=True)),
                ('default_gst_rate', models.DecimalField(decimal_places=2, default=18.0, max_digits=5)),
                ('cgst_rate', models.DecimalField(decimal_places=2, default=9.0, max_digits=5)),
                ('sgst_rate', models.DecimalField(decimal_places=2, default=9.0, max_digits=5)),
                ('igst_rate', models.DecimalField(decimal_places=2, default=18.0, max_digits=5)),
                ('utgst_rate', models.DecimalField(decimal_places=2, default=9.0, max_digits=5)),
                ('hsn_required', models.BooleanField(default=True)),
                ('price_tax_type', models.CharField(choices=[('exclusive', 'Tax Exclusive'), ('inclusive', 'Tax Inclusive')], default='exclusive', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='WarehouseConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_multiple_warehouses', models.BooleanField(default=True)),
                ('code_format', models.CharField(default='WH-{001}', max_length=20)),
                ('allow_warehouse_transfer', models.BooleanField(default=True)),
                ('require_transfer_approval', models.BooleanField(default=True)),
                ('allow_negative_stock', models.BooleanField(default=False)),
            ],
        ),
    ]
