# Generated by Django 5.2.16 on 2026-08-09 06:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('low_stock', 'Low Stock Alert'), ('out_of_stock', 'Out of Stock Alert'), ('over_stock', 'Over Stock Alert'), ('purchase', 'Purchase Alert'), ('transfer', 'Stock Transfer Alert'), ('ocr', 'AI OCR Scanner Alert'), ('payment_due', 'Payment Due Alert'), ('backup', 'Backup Alert'), ('security', 'Security Alert'), ('system', 'System Message')], default='system', max_length=30)),
                ('priority', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('normal', 'Normal'), ('low', 'Low')], default='normal', max_length=20)),
                ('module', models.CharField(default='System', max_length=50)),
                ('related_record_type', models.CharField(blank=True, max_length=50, null=True)),
                ('related_record_id', models.CharField(blank=True, max_length=50, null=True)),
                ('action_url', models.CharField(blank=True, max_length=255, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_low_stock', models.BooleanField(default=True)),
                ('notify_out_of_stock', models.BooleanField(default=True)),
                ('notify_purchases', models.BooleanField(default=True)),
                ('notify_transfers', models.BooleanField(default=True)),
                ('notify_ocr', models.BooleanField(default=True)),
                ('notify_backups', models.BooleanField(default=True)),
                ('notify_security', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
