# Generated by Django 5.2.16 on 2026-08-08 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='warehouse',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='warehouse',
            name='alternate_phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='capacity_unit',
            field=models.CharField(default='Units', help_text='e.g. Sq Ft, Boxes, Units, Cartons', max_length=50),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='warehouses/'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='manager_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='opening_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='operating_hours',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='pin_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='total_capacity',
            field=models.IntegerField(default=10000, help_text='Configurable volume or weight limit'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='warehouse_type',
            field=models.CharField(choices=[('main', 'Main Warehouse'), ('godown', 'Godown'), ('branch', 'Branch'), ('distribution', 'Distribution Center'), ('store', 'Store')], default='godown', max_length=30),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.CreateModel(
            name='WarehouseHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('detail', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='products.warehouse')),
            ],
            options={
                'verbose_name_plural': 'Warehouse Histories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WarehouseStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('min_stock_level', models.IntegerField(default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_stocks', to='products.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_stocks', to='products.warehouse')),
            ],
            options={
                'verbose_name_plural': 'Warehouse Stocks',
                'unique_together': {('product', 'warehouse')},
            },
        ),
    ]
