# Generated by Django 5.2.16 on 2026-08-09 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_warehouse_options_warehouse_alternate_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehousestock',
            name='batch_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='warehousestock',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='warehousestock',
            name='max_stock_level',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='warehousestock',
            name='rack_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
