# Generated by Django 5.2.16 on 2026-08-09 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_warehousestock_batch_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='warehousestock',
            options={'ordering': ['-updated_at'], 'verbose_name_plural': 'Warehouse Stocks'},
        ),
    ]
