# Generated by Django 5.2.16 on 2026-08-09 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_warehousestock_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='has_batch_tracking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='has_expiry_tracking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='has_serial_tracking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='require_batch_no',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='require_exp_date',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='require_mfg_date',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='require_serial_no',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='tracking_type',
            field=models.CharField(choices=[('normal', 'Normal Product'), ('batch', 'Batch Tracking'), ('expiry', 'Expiry Tracking'), ('serial', 'Serial Number Tracking'), ('batch_expiry', 'Batch + Expiry'), ('batch_serial', 'Batch + Serial Number'), ('all', 'Batch + Expiry + Serial')], default='normal', max_length=30),
        ),
    ]
